name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  vue-2:
    strategy:
      matrix:
        node: [16, 18]
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Using pnpm version 7.x.x
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.x.x

      - name: Using node version ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Building the project
        run: pnpm run build

      - name: Running tests
        run: pnpm run test:2-run

  vue-3:
    strategy:
      matrix:
        node: [16, 18]
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Using pnpm version 7.x.x
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.x.x

      - name: Using node version ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Building the project
        run: pnpm run build

      - name: Running tests
        run: pnpm run test:3-run

  dts:
    strategy:
      matrix:
        node: [16, 18]
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Using pnpm version 7.x.x
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.x.x

      - name: Using node version ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Building the project
        run: pnpm run build

      - name: Running tests
        run: pnpm run test:dts-only
