name: Testing

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  vue-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2

      - name: Installing pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x.x

      - name: Using node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Installing dependencies
        run: pnpm install

      - name: Building the project
        run: pnpm run build

      - name: Running tests
        run: pnpm run test:2

      - name: Running lint
        run: pnpm run lint

  vue-3:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2

      - name: Installing pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x.x

      - name: Using node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Installing dependencies
        run: pnpm install

      - name: Building the project
        run: pnpm run build

      - name: Running tests
        run: pnpm run test:2

      - name: Running lint
        run: pnpm run lint

  dts:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2

      - name: Installing pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x.x

      - name: Using node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Installing dependencies
        run: pnpm install

      - name: Building the project
        run: pnpm run build

      - name: Running tests
        run: pnpm run test:dts-only

      - name: Running lint
        run: pnpm run lint
